server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admindb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
